name: aria2
services:
  server:
    image: p3terx/aria2-pro:latest
    container_name: aria2-server
    restart: always
    pull_policy: always
    environment:
      - PUID=65534
      - PGID=65534
      - UMASK_SET=022
      - RPC_SECRET=P3TERX
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=${TZ:-America/New_York}
    volumes:
      - ${HOME}/Downloads/aria2:/downloads
      - /var/lib/srv/$USER/docker/p3terx/aria2-pro/latest/rootfs/config/aria2:/config
    ports:
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp
    networks:
      - aria

  web:
    image: p3terx/ariang:latest
    container_name: ariang
    restart: always
    pull_policy: always
    command: --port 6880 --ipv6
    ports:
      - 6880:6880
    networks:
      - aria

networks:
  aria:
    name: aria
    external: false
